### PR TITLE
fix #8 rename class to DHTStable to fix INCOMPATIBLE warning

### LINKED ISSUE #8: Loading From Arduino Library Manager Library Is Placed In INCOMPATIBLE Folder
On both Windows and Ubuntu Linux the screen shot below shows where the library is loaded.
Screenshot from 2021-05-24 12-11-23

### PR DESCRIPTION
**Pull request by RobTillaart**
-This is a breaking change as both the include files and class name is renamed.

### CODE REVIEW

**Comment by MrYsLab** [comment]
Thanks for the very quick response. Here is what I did.

I downloaded the develop branch, created a .zip, and installed it. The correct directory name was create/chosen. When I compile I do not get any warnings.

Would you know if there is any way to test a local library using the Arduino library manager? I tried putting the local .json file into the Preferences section of the IDE using a file://localhost URL, but it did not recognize the location.

**Comment by RobTillaart** [comment]
> Would you know if there is any way to test a local library using the Arduino library manager? 

Check - https://arduino.github.io/arduino-lint/latest/installation/
That is (one of the ) tools used to verify new libraries.

If the library is on GITHUB  you might install - https://github.com/arduino/arduino-lint-action
(I'am thinking about this, and want to test it coming month or so. 
If it works well it would mean updating 130 libraries, (so I probably wait until the winter comes....)

What I think is strange is that I didn't have the DHTStable library in the INCOMPATIBLE menu ?
(so I want to better understand the problem ...)

**Comment by RobTillaart** [comment]
Added the - https://github.com/arduino/arduino-lint-action  to this branch to see what it does.

**Comment by MrYsLab** [comment]
Do you need me to download again with the added arduino-lint-action?

I just tried installing the old version again on a fresh installation of Ubuntu 21.04 running in Virtualbox. I am running Arduino 1.8.15. With that, I still get the "incompatible." If I remove the old version from the libraries directory and install it with the updated repository, everything looks good.

I will look at the arduino-lint-action and try it out. I have only about 5 repositories that I will run it on, so it may not be too bad. Most of my stuff is in Python.

**Comment by RobTillaart** [comment]
>Do you need me to download again with the added arduino-lint-action?

No need, was just to inform you I added the lint thingie.

**Comment by MrYsLab** [comment]
Ok, thanks. I just tried arduino-lint on my code - thanks for the tip. 
Let me know if you want me to close the issue. As far as I am concerned, it is closed and you may close it if you wish.
Thanks again.

**Comment by MrYsLab** [comment]
I use the PyCharm Professional IDE. It incorporates a PEP8 tool (the equivalent of C lint). I also use JetBrains WebStorm for HTML/JavaScript and CLion for C/C++. All of their tools have a very similar user interface, making things easy to learn. JetBrains offers [a free license](https://www.jetbrains.com/shop/eform/opensource?returned=true&licenseRef=ARF9YTNGF4) to all their IDEs for open-source authors.
You probably noticed that I don't offer a set of unit tests for most of my projects. Because most of my projects interact with hardware, I find that by providing example code that exercises the hardware in conjunction with running the coverage tool built into PyCharm, I get better results than creating static unit tests that stub out the hardware. Just a personal preference.
Again, thanks for the excellent library and support.

**Comment by MrYsLab** [comment]
I forgot to mention, that CLion does not know what a .ino file is, so I just create a .cpp file and rename it later and test it in the Arduino IDE. There is an extension that deals with .ino files, but in the past, I found it to be difficult to use. I am going to try the latest version again and see if it has improved.

**Pull request merged**
