### PR TITLE
Update dht.cpp

### PR DESCRIPTION
**Pull request by PascalCorpsman**
Fix Bit set error from DHT22 Module, as the module does not set the highest bit in near 0 degree ranges. Tested with a refrigerator from -20 to 20 degree.

### CODE REVIEW

**Comment by RobTillaart** [comment]
Assume this is the same fix as in DHTNew?

**Comment by PascalCorpsman** [comment]
Yes and no,

it is the same when looking on the convertion between int and float. And a additional fix / Hack to resolve the missing highest Bit error.

During my tests it showed up, that the modul does not set the highest bit (signaling that it is a negative temperature) in the degree range -1 to 0 but all the other bits => this give a huge floating number arround 2^15. In my opinion this is a bug in the module. The only way to get out of this is by looking on the 0x40 Bit and "overwriting" the 0x80 bit with its value.

Changing the bit[2] will make the sum test invalid so this has to be done first.

=> The resulting version works as expected (in worst case this fix produces a off by 1 error in the range of -1 to 0 degree, what is much better than a off by 2^15 error :) )

I think but not tested, that you will have to add the lines:
    if (bits[2] & 0x40) 
    {
        bits[2] |= 0x80;
    } 

in dhtnew as well.

**Comment by RobTillaart** [comment]
> range -1 to 0
mmm. not good. 
This can be sensor dependent, so I must redo the freezer test here to see if my sensor also has the bug.
- If so, it should be fixed ==> assumption is that bug exists over sensor batches
- If not it should be documented ==> assumption it is batch /version specific)

**Comment by PascalCorpsman** [comment]
Well i tested it with 3 different dht22, all the same. But they were all bought at once so it could still be a batch thing ...

**Comment by RobTillaart** [comment]
testrun, here with DHTNew showed also serious trouble.
```
TIM	CNT	STAT	HUMI	TEMP	TIME	TYPE
1093682	1090	OK,	18.4,	0.5,	5328,	22
1094688	1091	WFR,	18.4,	0.5,	8,	22
1095690	1092	OK,	17.4,	0.3,	5224,	22
1096696	1093	WFR,	17.4,	0.3,	8,	22
1097698	1094	OK,	18.5,	0.2,	5260,	22
1098704	1095	WFR,	18.5,	0.2,	8,	22
1099706	1096	OK,	18.7,	0.1,	5264,	22
1100713	1097	WFR,	18.7,	0.1,	8,	22
1101715	1098	OK,	18.7,	0.0,	5252,	22
1102722	1099	WFR,	18.7,	0.0,	8,	22

OK 	CRC 	TOA 	TOB 	TOC 	TOD 	SNR 	BS 	WFR 	UNK
549	0	0	0	0	0	1	0	549	0	


TIM	CNT	STAT	HUMI	TEMP	TIME	TYPE
1103727	1100	OK,	18.8,	-3276.7,	5336,	22
1104735	1101	WFR,	18.8,	-3276.7,	8,	22
1105736	1102	OK,	17.9,	-3276.6,	5208,	22
1106744	1103	WFR,	17.9,	-3276.6,	8,	22
1107745	1104	OK,	19.0,	-3276.5,	5208,	22
1108752	1105	WFR,	19.0,	-3276.5,	8,	22
1109753	1106	OK,	19.1,	-3276.3,	5256,	22
1110761	1107	WFR,	19.1,	-3276.3,	8,	22
1111762	1108	OK,	19.2,	-3276.2,	5076,	22
1112769	1109	WFR,	19.2,	-3276.2,	8,	22

TIM	CNT	STAT	HUMI	TEMP	TIME	TYPE
1113772	1110	OK,	19.3,	-3276.1,	5188,	22
1114778	1111	WFR,	19.3,	-3276.1,	8,	22
1115780	1112	OK,	18.3,	-3276.0,	5348,	22
1116787	1113	WFR,	18.3,	-3276.0,	4,	22
1117789	1114	OK,	19.4,	-3275.8,	5116,	22
1118795	1115	WFR,	19.4,	-3275.8,	4,	22
1119797	1116	OK,	19.5,	-3275.7,	5256,	22
1120804	1117	WFR,	19.5,	-3275.7,	8,	22
1121806	1118	OK,	19.6,	-3275.6,	5068,	22
1122812	1119	WFR,	19.6,	-3275.6,	8,	22
```

**Comment by PascalCorpsman** [comment]
how do you test this, is this because of my pull request ?

**Comment by PascalCorpsman** [comment]
-3275.6 was 0x800C in Hex => so my patch would result this to 1.2 Degree

**Comment by RobTillaart** [comment]
> how do you test this, is this because of my pull request ?

DHTNew 0.4.1 with endless.ino example

> -3275.6 was 0x800C in Hex => so my patch would result this to 1.2 Degree
Confirm the 0x800C

I added hex dump in the .cpp of DHTNew and after 2 iterations I got temperature right
(log cleaned)
```
000D    1.3 
000B    1.1
000A    1.0
0008    0.8
0006    0.6
0005    0.5
0004    0.4
0002    0.2
0001    0.1
0000    0.0
8001    -0.1
8003    -0.3
8005    -0.5
8006    -0.6
8008    -0.8
8009    -0.9
800A    -1.0
800B    -1.1
800D    -1.3
800F    -1.5
8010    -1.6
8011    -1.7
8012    -1.8
8014    -2.0
8015    -2.1
8017    -2.3
8016    -2.2
8015    -2.1
8013    -1.9
8010    -1.6
800F    -1.5
800C    -1.2
800A    -1.0
8008    -0.8
8006    -0.6
8004    -0.4
8001    -0.1
0000    0.0
0003    0.3
0006    0.6
```
So sign bit = 0x80 
Remainder is absolute temperature. 

Change snippet in DHTNEW.cpp
```cpp
  if (_type == 22) // DHT22, DHT33, DHT44, compatible
  {
    _humidity =    (_bits[0] * 256 + _bits[1]) * 0.1;
    /* _temperature = ((_bits[2] & 0x7F) * 256 + _bits[3]) * 0.1; */
    int16_t val= ((_bits[2] & 0x7F) << 8 | _bits[3]);
    _temperature = val * 0.1;
    if (_bits[2] & 0x80) _temperature = -_temperature;
    
    // HEXDUMP
    Serial.println();
    if (_bits[2] < 0x10) Serial.print(0);
    Serial.print(_bits[2], HEX);
    if (_bits[3] < 0x10) Serial.print(0);
    Serial.print(_bits[3], HEX);
    Serial.print("    ");
    Serial.print(_temperature, 1);
  }
  else // if (_type == 11)  // DHT11, DH12, compatible
  {
    _humidity = _bits[0] + _bits[1] * 0.1;
    _temperature = _bits[2] + _bits[3] * 0.1;
  }
```

**Comment by RobTillaart** [comment]
Am doing a longer test now with DHTNew and if it succeeds I'll update all relevant libraries.

**Comment by RobTillaart** [comment]
test sketch
```cpp
//
//    FILE: dhtnew_debug.ino
//  AUTHOR: Rob Tillaart
// VERSION: 0.1.0
// PURPOSE: DHTNEW library test sketch for Arduino
//     URL: https://github.com/RobTillaart/DHTNew
//
// HISTORY:
// 0.1.0    2020-12-15
//
// DHT PIN layout from left to right
// =================================
// FRONT : DESCRIPTION
// pin 1 : VCC
// pin 2 : DATA
// pin 3 : Not Connected
// pin 4 : GND

#include <dhtnew.h>

DHTNEW mySensor(6);

void setup()
{
  Serial.begin(115200);
  Serial.println("dhtnew_test.ino");
  Serial.print("LIBRARY VERSION: ");
  Serial.println(DHTNEW_LIB_VERSION);
  Serial.println();
}

void loop()
{
  delay(2000);
  mySensor.read();    // put print statements in .cpp file
}

// END OF FILE
```

**Comment by RobTillaart** [comment]
I noted that testing the DHT22 in my freezer did molest the humidity readings.  
Got now a constant 99.9%

**Comment by PascalCorpsman** [comment]
Thanks, i will tomorrow write a hex dump version that i can run and post the results ;)

**Comment by RobTillaart** [comment]
I tried the DHTStable 0.2.6 in the freezer and it did not see the error you mention.
To be sure I will ran the test tomorrow again.

**Hypothesis**
Just thinking out loud,  when the 0x40 bit is set instead of the 0x80 bit, that could mean there is a problem with the timing of the bits. Imagine the bit is set just a bit too early then the wrong bit is set in the **bits[]** array. Normally  the 0x40 bit will never be set, as only the sign bit and the two lowest bits of bits[2] are set (temperature is max 100 so other bits will not get set)

**Question**
Can you please verify if the problem does exist with the latest DHTNew 0.4.2.?
That one has been fixed to work with my DHT22 and my freezer :)

**Comment by RobTillaart** [comment]
**Question**
Which board are you using? 
- UNO? 
- ESP32?

----
A few moments ago I tried DHTlib 0.1.30 without mentioned problem. 
( too late to investigate further, tomorrow another day )

**Comment by PascalCorpsman** [comment]
I am Back,
First i use a Arduino Nano (cheap china version) with a Atmega328P
i copied your test sketch modified Pin to 2 and baud to 38400 

i now did some test runs;
> DHTNew:
> Test 1:
> 000B    1.1
> 000A    1.0
> 0009    0.9
> 0007    0.7
> 0006    0.6
> 0005    0.5
> 0003    0.3
> 0002    0.2
> 0001    0.1
> FFFF    -3276.7
> FFFE    -3276.6
> FFFD    -3276.5
> FFFB    -3276.3
> FFFA    -3276.2
> FFF9    -3276.1
> FFF8    -3276.0
> FFF7    -3275.9
> 
> Test 2:
> 0009    0.9
> 0007    0.7
> 0005    0.5
> 0003    0.3
> 0001    0.1
> 8000    0.0
> FFFF    -3276.7
> FFFD    -3276.5
> FFFB    -3276.3
> FFFA    -3276.2
> FFF8    -3276.0
> FFF6    -3275.8
> FFF5    -3275.7
> 
> Test 3:
> 0009    0.9
> 0007    0.7
> 0006    0.6
> 0002    0.2
> 0000    0.0
> 8000    0.0
> FFFE    -3276.6
> FFFC    -3276.4
> FFFB    -3276.3
> FFF9    -3276.1
> FFF7    -3275.9
> FFF6    -3275.8
> 
> Test 4:
> 0009    0.9
> 0007    0.7
> 0005    0.5
> 0003    0.3
> 0001    0.1
> 8000    0.0
> FFFF    -3276.7
> FFFD    -3276.5
> FFFB    -3276.3
> FFF9    -3276.1
> FFF7    -3275.9
> FFF6    -3275.8
> 
> Test 5:
> 0009    0.9
> 0007    0.7
> 0005    0.5
> 0003    0.3
> 0001    0.1
> 8000    0.0
> FFFE    -3276.6
> FFFC    -3276.4
> FFFA    -3276.2
> FFF8    -3276.0
> FFF6    -3275.8
> 
> DHTStable: (my modifications)
> 0009    0.9
> 0006    0.6
> 0004    0.4
> 0001    0.1
> 8000    -3276.8
> FFFE    -0.2
> FFFB    -0.5
> FFF9    -0.7
> FFF7    -0.9
> FFF5    -1.1
> FFF3    -1.3
> FFF1    -1.5


=> i can not reproduce my own error with the 0x40 Bit, maybe this is because my other build is at 80%RAM usage and i still get this Compiler warnings about possible malfunction..

=> All testruns no matter if dhtnew or dhtstable showed that my dht22 module is sending 2complement numbers except for 0

**Comment by RobTillaart** [comment]
Good morning,

**Observation**
What is striking is that you get complete other bit patterns than I have. 
That's why it fails in all 3 libraries - as they essentially have the same math for temperature. Also the ADAFruit library uses similar math for temperature.

**Analysis**
The root cause seems to be that your sensor uses a sort of **one complements** representation
- http://www.cs.uwm.edu/classes/cs315/Bacon/Lecture/HTML/ch04s12.html

It is not an 100% implementation of **OC** as 0xFFFF represents -1 and not 0
- https://www.electronics-tutorials.ws/binary/signed-binary-numbers.html

And mine uses **two complements**
- http://www.cs.uwm.edu/classes/cs315/Bacon/Lecture/HTML/ch04s13.html

**Proposal**
The solution for the library (maybe all of them) is to add a bool flag to be able to switch between these two representations.

Code snippets
```cpp
uint8_t _bitrep = 2;  // default, as that is current behavior that one does not want to break;

void setBitRepresentation(uint8_t mm) { _bitrep = (mm ==1 ? 1 : 2; };
uint8_t getBitRepresentation() { return _bitrep ; };
```

The **read()** code should check the **_bitRep** flag and use the right math.

**Comment by PascalCorpsman** [comment]
How about this:

`
  if (_type == 22) // DHT22, DHT33, DHT44, compatible
  {
    _humidity =    (_bits[0] * 256 + _bits[1]) * 0.1;

    int16_t val;
    switch (_bits[2] >>6)
    {
      case 0: /* Positive Number 2-Complement */
        val= (_bits[2] << 8 | _bits[3]);
        break;

      case 3: /* Negative Number 2-Complement */
      case 1: /* Negative Number 2-Complement, but missing highest Bit */
        val= (_bits[2] << 8 | _bits[3] | 0x8000);
        break;

      case 2: /* Implementation as expceted according datasheet, but Negative*/
        val= ((_bits[2] & 0x7F) << 8 | _bits[3]);
        val = -val;
        break;
    }
    
    _temperature = val * 0.1;
    
    // HEXDUMP
    Serial.println();
    if (_bits[2] < 0x10) Serial.print(0);
    Serial.print(_bits[2], HEX);
    if (_bits[3] < 0x10) Serial.print(0);
    Serial.print(_bits[3], HEX);
    Serial.print("    ");
    Serial.print(_temperature, 1);
  }
`

**Comment by RobTillaart** [comment]
**TIP**: add cpp after the three backquotes to get syntax highlighting

```cpp
  case 3: /* Negative Number 2-Complement */
  case 1: /* Negative Number 2-Complement, but missing highest Bit */
    val= (_bits[2] << 8 | _bits[3] | 0x8000);
    break;
```
Will fail,  If the 0x40 bit is set e.g  0x4001 it becomes 0xC001 , while you want 0x8001

I am no fan of these kind of corrective code unless 
- it occurs often and 
- it can not be solved at the source (it seems to me a timing during bits clocking in)

**Comment by RobTillaart** [comment]
**Further analysis**
https://en.wikipedia.org/wiki/Signed_number_representations#Comparison_table

Based on this my previous analysis is not correct, but in the right direction.

According from the Wikipedia link above:
- my DHT22 gives a SIGN and MAGNITUDE. 0x8001 = -1
- your DHT22 sensor is ONE or TWO COMPLEMENT, it is not possible to determine from the bit pattern itself. 
  effectively depending on the scheme taken it gets an offset of 0.1°C

I have checked if other DHT family sensors mention other one or two complement but all I can find is SIGN MAGN. descriptions in articles . 
https://cdn.boxtec.ch/pub/diverse/rht04.pdf  (a.k.a. DHT33)  is a -40 - 100°C but it uses the same SIGN MAG scheme.
Can you remember where you bought them?

One option I really consider is that the sensor is in fact not a genuine one. 
Question that arises is if it should be supported in the library then. How many are there in the field?

**Comment by RobTillaart** [comment]
Test sketch for different formats.

```cpp
void setup()
{
  Serial.begin(115200);

  printOC(0x00, 0xFF);
  printTC(0x00, 0xFF);
  printSignMag(0x00, 0xFF);
  
  printOC(0xFF, 0xFF);
  printTC(0xFF, 0xFF);
  printSignMag(0x80, 0x01);

  Serial.println();
}

void loop()
{
}

void printOC(uint8_t h, uint8_t l)  // One Complements
{
  int16_t val;
  float temperature;
  if (h & 0x80) // negative
  {
    h ^= 0xFF;
    l ^= 0xFF;
    val = h << 8 | l;
    val = -val;
  }
  else
  {
    val = h << 8 | l;
  }
  temperature = val * 0.1;
  Serial.print("OC\t");
  Serial.println(temperature);
}

void printTC(uint8_t h, uint8_t l)  // Two Complements
{
  int16_t val = h << 8 | l;
  float temperature = val * 0.1;
  Serial.print("TC\t");
  Serial.println(temperature);
}

void printSignMag(uint8_t h, uint8_t l)  // Sign Magnitude
{
  int16_t val = ((h & 0x7F) << 8) | l;
  float temperature = val * 0.1;
  if (h & 0x80) temperature = -temperature;
  Serial.print("SM\t");
  Serial.println(temperature);
}
```

My search sofar only showed the **DS3231** to use a two complements temperature format.

**Comment by PascalCorpsman** [comment]
i bought the modules on Ebay two weeks ago here is the link:

https://www.ebay.de/itm/2x-DHT22-Temperatur-und-Luftfeuchtigkeitssensor-f%C3%BCr-Arduino-Funduino-Raspberry/163692661884?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2057872.m2749.l2649

**Comment by RobTillaart** [comment]
> i bought the modules on Ebay two weeks ago here is the link:
> 
> https://www.ebay.de/itm/2x-DHT22-Temperatur-und-Luftfeuchtigkeitssensor-f%C3%BCr-Arduino-Funduino-Raspberry/163692661884?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2057872.m2749.l2649

Thanks,
On the image in the add stands AM2302 on the sensor, which is indeed a DHT22 compatible.
https://cdn-shop.adafruit.com/datasheets/Digital+humidity+and+temperature+sensor+AM2302.pdf
==> Has the SIGN MAGN format too

**Comment by PascalCorpsman** [comment]
Well whats struggling me is, that the Byte Check is always OK, so there could be no transmission error ..

**Comment by RobTillaart** [comment]
To be  continued after Christmas....

**Comment by RobTillaart** [comment]
Redid the investigation from scratch and minimized the solution.
tested on ESP32 and AVR
made a new PR to keep code in sync with DHTNew and DHTlib 

https://github.com/RobTillaart/DHTstable/pull/5 

Thanks for pointing out the problem.

**Pull request closed without merging**
